include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Ruijie Campus Autologin
LUCI_DEPENDS:=+ruijie-campus-autologin
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
